name: Build iOS

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rust-src

    - name: Add aarch64-apple-ios target
      run: rustup target add aarch64-apple-ios

    - name: Cache Cargo dependencies (rust-cache)
      uses: swatinem/rust-cache@v2

    - name: Build libtitanox
      run: |
        git clone https://github.com/Ragekill3377/Titanox.git $HOME/titanox-src

        git clone --recursive https://github.com/theos/theos.git $HOME/theos
        export THEOS=$HOME/theos

        brew install ldid coreutils

        cd $HOME/titanox-src/libtitanox

        sed -i '' 's/TARGET := iphone:clang:13.7/TARGET := iphone:clang:latest/' Makefile
        sed -i '' 's/THEOS = \/home\/rage\/theos/# THEOS = \/home\/rage\/theos/' Makefile
        sed -i '' 's/SYSROOT = $(THEOS)\/sdks\/iPhoneOS13.7.sdk/# SYSROOT = $(THEOS)\/sdks\/iPhoneOS13.7.sdk/' Makefile

        sed -i '' '/^LIBRARY_NAME = libtitanox/ a \
        libtitanox_TYPE = static
        ' Makefile

        make package || true

        cp .theos/obj/libtitanox.a $GITHUB_WORKSPACE/vendor/titanox/lib/libtitanox.a

    - name: Build for iOS
      run: |
        export SDKROOT=$(xcrun --sdk iphoneos --show-sdk-path)

        export RUSTFLAGS="\
         -C link-arg=-isysroot \
         -C link-arg=$SDKROOT \
         -C link-arg=-target \
         -C link-arg=aarch64-apple-ios13.2 \
         -C link-arg=-miphoneos-version-min=13.2 \
         -C link-arg=-lc++ \
         -C link-arg=-framework \
         -C link-arg=Security \
         -C link-arg=-framework \
         -C link-arg=CoreFoundation \
         -C link-arg=-Wl,-interposable \
         -C link-arg=-Wl,-U,_dlopen"

        CARGO_TARGET_AARCH64_APPLE_IOS_LINKER=$(xcrun --find clang) \
        CARGO_INCREMENTAL=0 \
        cargo build --target aarch64-apple-ios --verbose

    - name: Upload iOS Library
      uses: actions/upload-artifact@v4
      with:
        name: libhachimi-ios
        path: target/aarch64-apple-ios/debug/libhachimi.dylib
